config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sailors do
    resources :sailor_powers, only: [:new, :create]
  end
  resources :sailor_powers, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :sailor_powers
  has_many :sailors, through: :sailor_powers

  validates :name, presence: true, uniqueness: true
end

app/models/sailor.rb
class Sailor < ApplicationRecord
  has_many :sailor_powers, dependent: :destroy
  has_many :powers, through: :sailor_powers
  has_one_attached :photo

  validates :name, presence: true
  validates :battle_name, presence: true, uniqueness: :true
  validates :planet, presence: :true
end

app/models/sailor_power.rb
class SailorPower < ApplicationRecord
  belongs_to :sailor
  belongs_to :power

  validates :power, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @sailors = Sailor.last(2).reverse # Sailor.all.order(created_at: :desc).limit(3)
  end
end

app/controllers/sailor_powers_controller.rb
class SailorPowersController < ApplicationController
  def new
    @sailor = Sailor.find(params[:sailor_id])
    @sailor_power = SailorPower.new
  end

  def create
    @sailor = Sailor.find(params[:sailor_id])
    @sailor_power = SailorPower.new(sailor_power_params)
    @sailor_power.sailor = @sailor
    if @sailor_power.save
      redirect_to sailor_path(@sailor)
    else
      render :new
    end
  end

  def destroy
    @sailor_power = SailorPower.find(params[:id])
    @sailor_power.destroy
    redirect_to sailor_path(@sailor_power.sailor)
  end

  private

  def sailor_power_params
    params.require(:sailor_power).permit(:power_id)
  end
end

app/controllers/sailors_controller.rb
class SailorsController < ApplicationController
  before_action :set_sailor, only: [:show, :edit, :update, :destroy]
  def index
    @sailors = Sailor.all
  end

  def show
    @sailor_power = SailorPower.new
  end

  def new
    @sailor = Sailor.new
  end

  def create
    @sailor = Sailor.new(sailor_params)
    if @sailor.save
      redirect_to sailor_path(@sailor)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sailor.update(sailor_params)
      redirect_to @sailor, notice: 'Sailor Warrior updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @sailor.destroy
    redirect_to sailors_path, notice: 'Sailor Warrior was successfully deleted.'
  end

  private

  def sailor_params
    params.require(:sailor).permit(:name, :battle_name, :planet, :photo)
  end

  def set_sailor
    @sailor = Sailor.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>🌙Sailor Maker</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="flex-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner"> <!-- style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(assets/bg_1.jpg);"> -->
  <div class="container">
    <h1>Sailor Maker</h1>
    <p class="p-big">
      <span id="banner-typed-text"></span>
    </p>
    <%= link_to 'Start Now', new_sailor_path, class: "button-pink" %>
  </div>
</div>

<div class="container my-5">
  <h2 class="s-dark-pink">
    <%= link_to 'View all Sailor Warriors', sailors_path %>
  </h2>
  <p class="s-dark-pink">Last Added Warriors</p>
  <div class="d-flex">
    <%= render 'sailors/card_small', sailors: @sailors %>
  </div>
</div>

app/views/sailor_powers/_form.html.erb
<%= simple_form_for [@sailor, @sailor_power] do |f| %>
  <%= f.association :power %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/sailor_powers/new.html.erb
<div class="container">
  <h1>Add a new Sailor Power</h1>
  <%= render 'form' %>
</div>

app/views/sailors/_card_small.html.erb
<% @sailors.each do |sailor| %>
  <div class="col-md-12 col-lg-6">
    <%= link_to sailor_path(sailor) do %>
      <% if sailor.photo.attached? %>
        <div class="card-bg" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path sailor.photo.key, responsive: :true, width: 400, crop: :fit %>')">
          <p class="card-bg-content"><%= sailor.battle_name %> </p>
        </div>
      <% else %>
        <div class="card-bg" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('https://res.cloudinary.com/dtewjoisz/image/upload/v1582382369/Tng8w78eGYPjYPMiRWPnXzHX.jpg'); width: 400px;">
          <p class="card-bg-content"><%= sailor.battle_name %> </p>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/sailors/_form.html.erb
<div class="container my-3">
  <%= simple_form_for @sailor do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :battle_name %>
      <%= f.input :planet %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-primary my-3" %>
    </div>
  <% end %>
</div>

app/views/sailors/edit.html.erb
<div class="container">
  <h1>Edit <%= @sailor.name %></h1>
  <%= render 'form' %>
  <%= link_to 'Back', sailor_path(@sailor) %>
  <%= link_to 'All Sailors', sailors_path %>
</div>

app/views/sailors/index.html.erb
<div class="container">
  <div class="cards row">
    <%= render 'card_small', sailors: @sailors %>
  </div>
</div>

app/views/sailors/new.html.erb
<div class="container">
  <h1>Create a New Sailor Warrior</h1>
  <%= render 'form' %>
  <div class="container">
    <h3 class="mb-3">
      <%= link_to sailors_path do%>
        <i class="far fa-moon"></i> Back
      <% end %>
    </h3>
  </div>
</div>

app/views/sailors/show.html.erb
<div class="container mt-3">
  <div class="card card-sailor mb-3" style="max-width: 900px;">
    <div class="row no-gutters">
      <div class="col-md-6 col-lg-4">
        <% if @sailor.photo.attached? %>
          <%= cl_image_tag @sailor.photo.key, height: 400, width: 300, crop: :fill, radius: 20, class: "card-sailor-img ml-2" %>
        <% else %>
          <%= image_tag 'sailor_moon.jpg', height: 400, width: 300, crop: :fill, radius: 20, class: "card-sailor-img ml-2" %>
        <% end %>
      </div>
      <div class="col-md-6 col-lg-4">
        <div class="card-body">
          <h1 class="card-title card-sailor-title">
            <%= @sailor.battle_name %>
          </h1>
          <p class="card-text">
            Planet: <%= @sailor.planet %>
          </p>
          <p class="card-text">
            Name: <%= @sailor.name %>
          </p>
          <p class="card-sailor-title">Powers</p>
          <% @sailor.sailor_powers.each do |power| %>
            <p> 
              <span class="badge badge-pill badge-primary">
                <%= power.power.name %>
              </span> 
              <span class="badge badge-pill badge-info">
                <%= power.power.element %>
              </span> 
              <span>
              <%= link_to sailor_power_path(power), method: "delete" do %>
                <i class="fas fa-minus-circle card-sailor-title"></i>
              </span>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <div class="card-body mt-2">
          <h3 class="card-sailor-text">Add powers</h3>
          <p class="card-text">
            <%= render 'sailor_powers/form', sailor: @sailor, sailor_power: @sailor_power, class: "card-sailor-form" %>
          </p>
          
          <h3 class="card-text card-sailor-text mt-3">
            <%= link_to edit_sailor_path do %>
              <i class="far fa-edit"></i> Edit Sailor
            <% end %>
          </h3>
          <h3 class="card-text card-sailor-text">
            <%= link_to sailor_path(@sailor), method: "delete" do %>
              <i class="fas fa-trash-alt"></i> Delete Sailor
            <% end %>
          </h3>
        </div>
      </div>
    </div>
  </div>
  <div>
    <h3><%= link_to sailors_path do%>
      <i class="far fa-moon"></i> Back
    <% end %>
    </h3>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="https://en.wikipedia.org/wiki/List_of_Sailor_Moon_characters"><i class="fab fa-wikipedia-w"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light nav-pink-bg">
  <%= link_to sailors_path, class: "navbar-brand h-link" do %>
    <h1 class="navi-title"><i class="far fa-moon s-dark-pink"></i> <span class="s-blue">Sailor Warriors</span></h1>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to root_path do %>
          <i class="fas fa-home navi-link"></i> Home
        <% end %>
      </li>
    </ul>
    <%= link_to new_sailor_path do %>
      <p class="styled-link navi-link"><i class="fas fa-plus"></i> Create a Sailor Warrior </p>
    <% end %>
  </div>
</nav>